server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG

#wire logging — вы увидите все HTTP-запросы и ответы,
#включая заголовки и тело (полезно для отладки)
reactor:
  netty:
    http:
      client:
        wiretap: true
      server:
        wiretap: true

spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: main_service_route
          uri: lb://main-service
          predicates:
            - Path=/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true #— говорит Eureka использовать IP вместо hostname при регистрации сервиса. Это помогает избежать проблем с резолвом имён в сложных сетях.