logging:
  level:
    ru.yandex.practicum: debug
    root: info

grpc:
  server:
    port: 0

server:
  port: 0

kafka:
  topic: stats.user-actions.v1
  bootstrap-server: localhost:9092
  retriesCount: 5
  retryBackOffMs: 1000
  isIdempotence: true
  batchSize: 10000
  lingerMs: 5