server:
  port: 0

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: dbuser
    password: 12345
    url: jdbc:postgresql://localhost:6542/maindb
  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
  sql:
    init:
      mode: always
  cloud:
    openfeign:
      okhttp:
        enabled: true
      circuitbreaker:
        enabled: true

grpc:
  client:
    collector:
      address: 'discovery:///collector'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    analyzer:
      address: 'discovery:///analyzer'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

app:
  name: ewm-main